### PR TITLE
cursor position at the end to enter search term

### PR DESCRIPTION
**Pull request by 1C0D**
It will unselect and put the cursor at the end to type directly the search terms

### CODE REVIEW

**Comment by 1C0D** [comment]
the file on my repo https://github.com/1C0D/search-from-directory-modif-cursor-pos/blob/main/src/main.ts 
this is putting the cursor in the input zone at the end of the search text

**Comment by 1C0D** [comment]
Added to the editor menu to search selected text in the parent directory of the active file

**Comment by justamanm** [comment]
i make some change about 

> the file on my repo https://github.com/1C0D/search-from-directory-modif-cursor-pos/blob/main/src/main.ts this is putting the cursor in the input zone at the end of the search text

Great job! and i make a small improvement base on your work, https://github.com/justamanm/search-from-directory-modif-cursor-pos/blob/fix-cursor-at-front/src/main.ts

**Comment by 1C0D** [comment]
- I put the version back to 0.0.1 maybe easy to accept pull requests.
- I repackaged the repo with Yarn
- So now when selecting a word an opening from the leaf it's selecting the searched text
- Else from the explorer it's putting the cursor after the search prefix. (with a space between)

**Pull request closed without merging**
